version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  redis-insight:
    image: redis/redis-stack:latest
    container_name: redis-insight
    ports:
      - '8001:8001'
    environment:
      - HTTP_PORT=8001
      - REDIS_URI=redis://redis:6379
